/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsedAutoPartsRouteImport } from './routes/used-auto-parts'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SellYourJunkCarRouteImport } from './routes/sell-your-junk-car'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as JunkCarRemovalRouteImport } from './routes/junk-car-removal'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AutoRecyclingServicesRouteImport } from './routes/auto-recycling-services'
import { Route as AreasWeServeRouteImport } from './routes/areas-we-serve'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'

const UsedAutoPartsRoute = UsedAutoPartsRouteImport.update({
  id: '/used-auto-parts',
  path: '/used-auto-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SellYourJunkCarRoute = SellYourJunkCarRouteImport.update({
  id: '/sell-your-junk-car',
  path: '/sell-your-junk-car',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const JunkCarRemovalRoute = JunkCarRemovalRouteImport.update({
  id: '/junk-car-removal',
  path: '/junk-car-removal',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoRecyclingServicesRoute = AutoRecyclingServicesRouteImport.update({
  id: '/auto-recycling-services',
  path: '/auto-recycling-services',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasWeServeRoute = AreasWeServeRouteImport.update({
  id: '/areas-we-serve',
  path: '/areas-we-serve',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/areas-we-serve': typeof AreasWeServeRoute
  '/auto-recycling-services': typeof AutoRecyclingServicesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/junk-car-removal': typeof JunkCarRemovalRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sell-your-junk-car': typeof SellYourJunkCarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/used-auto-parts': typeof UsedAutoPartsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/areas-we-serve': typeof AreasWeServeRoute
  '/auto-recycling-services': typeof AutoRecyclingServicesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/junk-car-removal': typeof JunkCarRemovalRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sell-your-junk-car': typeof SellYourJunkCarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/used-auto-parts': typeof UsedAutoPartsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/areas-we-serve': typeof AreasWeServeRoute
  '/auto-recycling-services': typeof AutoRecyclingServicesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/junk-car-removal': typeof JunkCarRemovalRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sell-your-junk-car': typeof SellYourJunkCarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/used-auto-parts': typeof UsedAutoPartsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/areas-we-serve'
    | '/auto-recycling-services'
    | '/contact'
    | '/faq'
    | '/junk-car-removal'
    | '/llms.txt'
    | '/robots.txt'
    | '/sell-your-junk-car'
    | '/sitemap.xml'
    | '/used-auto-parts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/areas-we-serve'
    | '/auto-recycling-services'
    | '/contact'
    | '/faq'
    | '/junk-car-removal'
    | '/llms.txt'
    | '/robots.txt'
    | '/sell-your-junk-car'
    | '/sitemap.xml'
    | '/used-auto-parts'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/areas-we-serve'
    | '/auto-recycling-services'
    | '/contact'
    | '/faq'
    | '/junk-car-removal'
    | '/llms.txt'
    | '/robots.txt'
    | '/sell-your-junk-car'
    | '/sitemap.xml'
    | '/used-auto-parts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AreasWeServeRoute: typeof AreasWeServeRoute
  AutoRecyclingServicesRoute: typeof AutoRecyclingServicesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  JunkCarRemovalRoute: typeof JunkCarRemovalRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SellYourJunkCarRoute: typeof SellYourJunkCarRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UsedAutoPartsRoute: typeof UsedAutoPartsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/used-auto-parts': {
      id: '/used-auto-parts'
      path: '/used-auto-parts'
      fullPath: '/used-auto-parts'
      preLoaderRoute: typeof UsedAutoPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-your-junk-car': {
      id: '/sell-your-junk-car'
      path: '/sell-your-junk-car'
      fullPath: '/sell-your-junk-car'
      preLoaderRoute: typeof SellYourJunkCarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junk-car-removal': {
      id: '/junk-car-removal'
      path: '/junk-car-removal'
      fullPath: '/junk-car-removal'
      preLoaderRoute: typeof JunkCarRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-recycling-services': {
      id: '/auto-recycling-services'
      path: '/auto-recycling-services'
      fullPath: '/auto-recycling-services'
      preLoaderRoute: typeof AutoRecyclingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-we-serve': {
      id: '/areas-we-serve'
      path: '/areas-we-serve'
      fullPath: '/areas-we-serve'
      preLoaderRoute: typeof AreasWeServeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AreasWeServeRoute: AreasWeServeRoute,
  AutoRecyclingServicesRoute: AutoRecyclingServicesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  JunkCarRemovalRoute: JunkCarRemovalRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SellYourJunkCarRoute: SellYourJunkCarRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UsedAutoPartsRoute: UsedAutoPartsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
